version: "3.1"
services:
  texlive:
    image: mylatexlive
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./work:/root/work
      - ./app/styles:/usr/local/texlive/2019/texmf-dist/tex/latex/user_style
    command: sh -c "browser-sync start --server --files \"/root/work/tmp/*\" & latexmk --pvc /root/work/main.tex"
